### ISSUE TITLE
Reduce git repository size

### ISSUE THREAD

**Issue by jayaddison** [NearbyShops/Nearby-Shops-Android-app-Deprecated#26]
Would you like any help repairing the corruption in the Git repository you mention ( https://github.com/NearbyShops/Nearby-Shops-Android-app-Deprecated/commit/8b6c62df1b6438cb5a0ced34a80632adfe725bbc )?

**Comment by SumeetMoray** [comment]
no its not just the corruption in the git repository ... the size of the respsitory has become really huge reaching upto 100 mb. I put some images and gifs into it and that's why the size got increased so much !

There are also few bugs !

**Comment by jayaddison** [comment]
There are some good instructions at https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history that show how to remove files from a git repository permanently.  Following those should bring the repository size back down.

Bugs are a reality of software development.. it's probably better to keep a history and record of them in a single repository than to move to a new one.  You might forget about details and comments that could be important again in future.
